export type Species = {
  id: string;
  name: string;
  scientific: string;
  group: string;
  kingdom: string;
  phylum: string;
  className: string;
  order: string;
  family: string;
  genus: string;
  subspecies?: string;
  habitat: string;
  diet: string;
  range: string;
  summary: string;
  status: string;
  sensitive: boolean;
  wiki: string;
  gbif?: number;
  statusSource?: string;
  statusYear?: string;
  statusScope?: string;
  photo?: string;
  credit?: string;
  creditUrl?: string;
  license?: string;
};
export type Observation = {
  id: string;
  species: Species;
  photos: string[];
  date: string;
  region: string;
  notes: string;
  visibility: "private" | "friends";
  sensitive: boolean;
  lat: number | null;
  lng: number | null;
  favorite: boolean;
  created: string;
  owner?: string;
  ownerName?: string;
  likes?: number;
  liked?: boolean;
  comments?: number;
  demo?: boolean;
};
export type Profile = { id: string; name: string; bio: string; code: string };
export type Friend = { id: string; name: string; bio: string };
export type AppData = {
  session: { mode: "guest" | "account" };
  profile: Profile;
  observations: Observation[];
  feed: Observation[];
  friends: Friend[];
};
